[project]
name = "data-science-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ensure>=1.0.4",
    "fastapi>=0.141.1",
    "joblib>=1.5.3",
    "matplotlib>=3.11.1",
    "mlflow>=3.15.1",
    "notebook>=7.6.2",
    "numpy>=2.5.2",
    "pandas>=2.3.3",
    "python-box>=7.4.1",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.0",
    "tqdm>=4.70.0",
    "types-pyyaml>=6.0.12.20260815",
    "uvicorn>=0.52.4",
]
